# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 093e175297650fec9f9b283bd6c8cbde3f7fcd21259032ee7bfea65c0938eae648952eb41133740ef15a349d75d533f9f1a67b57019070dfcb78b351b4791c48

test:
  secret_key_base: 1e0f551a96dfd71d42e7bdfdde543c85cae48c67e547c5d01f73312c9318a86c02cd23946f994eb3c6cc2cdb6de1b33e8ec8bb999b55c146de4e912bce38bfc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
